# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/143QYmiTxhXC-mu44pU60O3t-WUul10mh
"""

class Solution(object):
    def maxFrequencyElements(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        freq = Counter(nums)
        max_ = max(freq.values())
        sum_ = 0
        for i in freq.values():
            if i == max_:
                sum_+=i
        return sum_